name: Sayvly
description: "Sayvly mobile app"
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  go_router: ^13.0.1
  google_sign_in: ^6.2.1
  kakao_flutter_sdk_user: ^1.9.0
  flutter_naver_login: ^2.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  image_picker: ^1.0.7
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#E98F79"
  adaptive_icon_foreground: "assets/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#E98F79"
  image: "assets/icon.png"
  color_dark: "#E98F79"
  image_dark: "assets/icon.png"
  android_12:
    color: "#E98F79"
    icon_background_color: "#E98F79"
    image: "assets/icon.png"
    color_dark: "#E98F79"
    icon_background_color_dark: "#E98F79"
    image_dark: "assets/icon.png"
  ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900


